### ISSUE TITLE
qq加群申请被过滤

### ISSUE THREAD

**Issue by RAINighty** [Colerar/bikkuri#1]
如题，有些人的账号因为一些原因被qq过滤了，而机器人不会搭理那些被过滤的申请，看看有没有办法解决？

**Comment by Colerar** [comment]
Mirai 中对申请进群事件无更多细分，也没有过滤相关的属性。

我印象中，提示有「该帐号存在风险，请谨慎操作」的入群申请是会受理的……

若在正常 QQ 客户端中也无法看到，恐怕没有办法。

**Comment by Colerar** [comment]
目前暂无解决办法
