### ISSUE TITLE
机器人加审核群需人工同意，后续运行正常

### ISSUE THREAD

**Issue by RAINighty** [Colerar/bikkuri#63]
如题

环境：程序每天0点、12点被kill，0点1分、12点1分启动

**Comment by Colerar** [comment]
建议重启时间错开直播上舰高峰期，因为申请列表是存在内存里的。后续可能会考虑添加持久化的功能，以确保重启不丢列表。

**Comment by Colerar** [comment]
这是预期行为，如果申请积压太久，可以考虑加大同时审核人数（如同时审核 3 人：`/config --queue 3`）和设置适当的超时时间。

由于新签名方式要重启，再加上申请列表不能持久化确实是一个痛点。
